version: "3.8"
services:
  speechtotextbot:
    build: .
    restart: unless-stopped
    command: "bash -c 'mount'"
    tmpfs: 
      - /home/speechtotextbot/ramdisk
    volumes:
      - ./pythonfiles/:/home/speechtotextbot/pythonfiles/
      - ./db/:/home/speechtotextbot/db/
      - ./secrets/:/home/speechtotextbot/secrets/
    command: bash -c "chmod -R 666 ./ramdisk"
    command: bash -c "python3 -u ./pythonfiles/main.py"
    